"""Parâmetros da sumarização ancorada (Apêndice do artigo)."""

MODELO_EXTRACAO = "gpt-6-luna"
MODELO_SINTESE = "gpt-6.1-sol"
MODELO_EMBEDDINGS = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

ESFORCO_EXTRACAO = "none"
ESFORCO_SINTESE = "low"
MAX_SAIDA_EXTRACAO = 12000
MAX_SAIDA_SINTESE = 8000

TIMEOUT_S = 180
TENTATIVAS = 3
MAX_PARALELO = 4

# Lotes: tokens contados com tiktoken/cl100k_base.
MAX_TOKENS_BLOCO = 10000
MAX_TOKENS_LOTE = 18000
MAX_BLOCOS_LOTE = 16

# Âncora recortada: maior trecho literal com ao menos 40 caracteres e 80% da citação.
ANCORA_MIN_CARACTERES = 40
ANCORA_MIN_FRACAO = 0.8

# Temas.
MIN_UNIDADES_PARA_SUBTEMAS = 20
MIN_TEMAS = 2
MAX_TEMAS = 10
MAX_CANDIDATOS = 20
UNIDADES_ALVO_POR_TEMA = 60
MAX_UNIDADES_POR_TEMA = 80
MAX_UNIDADES_APOS_FUSAO = 100
TOLERANCIA_MELHOR_ESCORE = 0.03
SIMILARIDADE_PARA_FUNDIR = 0.82
SIMILARIDADE_TITULOS_PARA_FUNDIR = 0.90
PENALIDADE_REDUNDANCIA = 0.35
PENALIDADE_UNITARIO = 0.15
PENALIDADE_COMPLEXIDADE = 0.01
